#ifndef RENDER_ENUMS_HPP_INCLUDED
#define RENDER_ENUMS_HPP_INCLUDED

enum RENDER_TEXTURE_ADDRESS_MODE
{
	RTAM_UNDEFINED	= 0,
	RTAM_WRAP		= 1,
	RTAM_CLAMP		= 2,
	RTAM_MIRROR		= 3,
	RTAM_FORCE_DWORD	= 0x7fffffff
};

enum RENDER_TEXTURE_FILTER_MODE
{
	RTFM_NONE			= 0,
	RTFM_POINT			= 1,
	RTFM_LINEAR			= 2,
	RTFM_ANISOTROPIC	= 3,
	RTFM_FORCE_DWORD	= 0x7fffffff
};

enum RENDER_TEXTURE_STAGE_ARGUMENT
{
	RTSA_UNDEFINED	= 0,
	RTSA_CURRENT	= 1,
	RTSA_DIFFUSE	= 2,
	RTSA_SPECULAR	= 3,
	RTSA_TEXTURE	= 4,
	RTSA_TFACTOR	= 5,
	RTSA_FORCE_DWORD	= 0x7fffffff
};

enum RENDER_TEXTURE_STAGE_OPERATION
{
	RTSO_DISABLE					= 1,
	RTSO_SELECTARG1					= 2,
	RTSO_SELECTARG2					= 3,
	RTSO_MODULATE					= 4,
	RTSO_MODULATE2					= 5,
	RTSO_MODULATE4					= 6,
	RTSO_ADD						= 7,
	RTSO_ADDSIGNED					= 8,
	RTSO_ADDSIGNED2					= 9,
	RTSO_SUB						= 10,
	RTSO_ADDSMOOTH					= 11,
	RTSO_BLEND_DIFFUSEALPHA			= 12,
	RTSO_BLEND_TEXALPHA				= 13,
	RTSO_BLEND_TFACTORALPHA			= 14,
	RTSO_BLEND_CURRENTALPHA			= 15,
	RTSO_BLEND_ALPHAPREMUL			= 16,
	RTSO_PREMUL						= 17,
	RTSO_MODULATEALPHA_ADDCOLOR		= 18,
	RTSO_MODULATECOLOR_ADDALPHA		= 19,
	RTSO_MODULATEINVCOLOR_ADDALPHA	= 20,
	RTSO_MODULATEINVALPHA_ADDCOLOR	= 21,
	RTSO_FORCE_DWORD				= 0x7fffffff
};

enum RENDER_CULL_MODE
{
	RCM_NONE	= 0,
	RCM_CW		= 1,
	RCM_CCW		= 2,
	RCM_FORCE_DWORD	= 0x7fffffff
};

enum RENDER_CMP_MODE
{
	RCMP_ALWAYS			= 0,
	RCMP_NEVER			= 1,
	RCMP_EQUAL			= 2,
	RCMP_LESS			= 3,
	RCMP_LESSEQUAL		= 4,
	RCMP_GREATER		= 5,
	RCMP_GREATEREQUAL	= 6,
	RCMP_NOTEQUAL		= 7,
	RCMP_FORCE_DWORD	= 0x7fffffff
};

enum RENDER_BLEND_MODE
{
	RBM_ZERO			= 0,
	RBM_ONE				= 1,
	RBM_SRCCOLOR		= 2,
	RBM_INVSRCCOLOR		= 3,
	RBM_SRCALPHA		= 4,
	RBM_INVSRCALPHA		= 5,
	RBM_DESTALPHA		= 6,
	RBM_INVDESTALPHA	= 7,
	RBM_DESTCOLOR		= 8,
	RBM_INVDESTCOLOR	= 9,
	RBM_SRCALPHASAT		= 10,
	RBM_FORCE_DWORD		= 0x7fffffff
};

#endif


































